### ISSUE TITLE
Add local repair module support

### ISSUE THREAD

**Issue by nikita-skakun** [MaruMaruOO/eve-fleet-simulator#6]
Currently, any fit that is active-tanked does not function as intended. One possible way would be to make the AI pulse the repair module every time the HP drops below a set value. This would be still quite unrealistic without simulating the capacitor and Nos/Neuts on other fits.

**Comment by MaruMaruOO** [comment]
@Xeros778 Thanks for the input.
The actual repair part is painless as it's mostly the same as remote repairs.
I did consider adding it without simulating the capacitor back when I added remote repairs.
I decided against it because I felt like it might be worse than nothing,  given local repairs are often extremely cap starved.

The plan was to add repairs alongside all capacitor interactions, but now you've brought it up I think a more short term solution might be in order.  

Perhaps we can have the initial capacitor implementation just cover Nos, Neuts and Repairs.
It should be much faster to implement, largely because it makes cap management much simpler for the AI.
It doesn't provide everything a full system would but it should be fairly close for repairs, what do you think?
